"""
Build a self-contained release zip that bundles BepInEx 5 + XUnity.AutoTranslator
+ this translation patch.

End-user just unzips into their game folder. No prior install needed.

Usage:
    python tools/build_release_full.py --game "C:/path/to/game"
    python tools/build_release_full.py --game "C:/Users/ocean/git/fd2/fd2re"

The --game folder must contain a working BepInEx + XUnity install
(this script copies their binaries from there).
"""
import argparse
import os
import shutil
import sys
import tempfile
import zipfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", required=True, help="Path to game folder with BepInEx already installed")
    ap.add_argument("--out", default=os.path.join(REPO_ROOT, "fd2re-ko-translation-full.zip"))
    args = ap.parse_args()

    game = os.path.abspath(args.game)
    out = os.path.abspath(args.out)

    if not os.path.isdir(os.path.join(game, "BepInEx", "core")):
        sys.exit(f"BepInEx not found in {game}. Install BepInEx first.")
    if not os.path.isdir(os.path.join(game, "BepInEx", "plugins", "XUnity.AutoTranslator")):
        sys.exit(f"XUnity.AutoTranslator not found in {game}. Install it first.")

    # Stage files in a temp dir, then zip from there
    with tempfile.TemporaryDirectory() as stage:
        # 1) BepInEx loader files at game-folder root
        for fn in ("winhttp.dll", "doorstop_config.ini", "changelog.txt"):
            src = os.path.join(game, fn)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(stage, fn))

        # 2) BepInEx/core
        shutil.copytree(
            os.path.join(game, "BepInEx", "core"),
            os.path.join(stage, "BepInEx", "core"),
        )

        # 3) BepInEx/plugins (XUnity.* only — skip user-added plugins)
        plugins_dst = os.path.join(stage, "BepInEx", "plugins")
        os.makedirs(plugins_dst)
        for name in os.listdir(os.path.join(game, "BepInEx", "plugins")):
            if name.startswith("XUnity") or name == "README (AutoTranslator).md":
                src = os.path.join(game, "BepInEx", "plugins", name)
                dst = os.path.join(plugins_dst, name)
                if os.path.isdir(src):
                    shutil.copytree(src, dst)
                else:
                    shutil.copy2(src, dst)

        # 4) BepInEx/patchers (may be empty but include for completeness)
        src_patchers = os.path.join(game, "BepInEx", "patchers")
        if os.path.isdir(src_patchers):
            shutil.copytree(src_patchers, os.path.join(stage, "BepInEx", "patchers"))

        # 5) Repo's translation + config
        for relpath in (
            ("BepInEx", "Translation", "ko", "Text", "_AutoGeneratedTranslations.txt"),
            ("BepInEx", "config", "AutoTranslatorConfig.ini"),
        ):
            src = os.path.join(REPO_ROOT, *relpath)
            dst = os.path.join(stage, *relpath)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)

        # 6) Licenses + readme — written from repo
        for fn in ("LICENSE-BepInEx.txt", "LICENSE-XUnity.txt", "READ-ME-한국어.txt"):
            src = os.path.join(REPO_ROOT, "release_assets", fn)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(stage, fn))

        # 7) Pack
        if os.path.exists(out):
            os.remove(out)
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
            for root, _, files in os.walk(stage):
                for f in files:
                    full = os.path.join(root, f)
                    arc = os.path.relpath(full, stage).replace(os.sep, "/")
                    zf.write(full, arc)

        # Report contents
        with zipfile.ZipFile(out) as zf:
            entries = zf.namelist()
        size = os.path.getsize(out)

    print(f"Built: {out}")
    print(f"  Size: {size/1024:.1f} KB")
    print(f"  Entries: {len(entries)}")
    print("  Top-level:")
    top = sorted({e.split('/', 1)[0] for e in entries})
    for t in top:
        print(f"    {t}")


if __name__ == "__main__":
    main()
