"""
Build _AutoGeneratedTranslations.txt from translations_phase1.py + translations_phase2.py.

Run from this directory:
    python build_xunity.py

Output is written to ../BepInEx/Translation/ko/Text/_AutoGeneratedTranslations.txt
relative to this script.

XUnity format: one entry per line as `chinese=korean`
- Real newlines in keys/values are escaped as literal \n
- Lines beginning with // are comments
"""
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
P1_JSON = os.path.join(HERE, "translations_phase1.json")
P2_JSON = os.path.join(HERE, "translations_phase2.json")
OUT = os.path.join(ROOT, "BepInEx", "Translation", "ko", "Text", "_AutoGeneratedTranslations.txt")


def run_phase_script(name):
    """Execute translations_phaseN.py to (re)generate its JSON."""
    path = os.path.join(HERE, name)
    if not os.path.exists(path):
        print(f"[skip] {name} not found")
        return
    print(f"[run] {name}")
    # Each phase script writes to a hardcoded path. Patch by exec-ing with overrides.
    # Simpler: just exec, the scripts now write next to themselves.
    g = {"__file__": path, "__name__": "__main__"}
    with open(path, encoding="utf-8") as f:
        exec(compile(f.read(), path, "exec"), g)


# Generate JSONs from .py sources
run_phase_script("translations_phase1.py")
run_phase_script("translations_phase2.py")

with open(P1_JSON, encoding="utf-8") as f:
    p1 = json.load(f)
with open(P2_JSON, encoding="utf-8") as f:
    p2 = json.load(f)

merged = {}
merged.update(p1)
merged.update(p2)
print(f"Total merged: {len(merged)}")

# Backup existing
if os.path.exists(OUT):
    shutil.copy2(OUT, OUT + ".bak")
    print(f"Backed up -> {OUT}.bak")


def escape(s):
    return s.replace("\r", "").replace("\n", r"\n")


lines = [
    "// FD2Re Korean translation",
    "// Generated by source/build_xunity.py from translations_phase1.py + translations_phase2.py",
    "// Edit translations directly here OR in the source .py files, then rebuild.",
    "",
]
for zh in sorted(merged.keys()):
    lines.append(f"{escape(zh)}={escape(merged[zh])}")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"\nWrote {len(merged)} entries to:")
print(f"  {OUT}")
